version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
    POSTGRES_USER: django
    POSTGRES_PASSWORD: django_1
    POSTGRES_DB: notes

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  backend:
    build:
      context: ./notes
#    ports:
    expose:
      - 8080
    command: bash -c "
    ./wait-for-postgres.sh db
    && python manage.py migrate
    && python manage.py create_data
#    && python manage.py runserver 0.0.0.0:8080
    & gunicorn library.wsgi -b 0.0.0.0:8080
    "
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8010:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx