# Generated by Django 4.1.1 on 2022-09-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='users',
            new_name='user_id',
        ),
    ]
