# Generated by Django 4.1.1 on 2022-10-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_age_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=2, max_length=126),
            preserve_default=False,
        ),
    ]
